export const EXERCISE_NAME_MAPPING = {
  "Barbell Incline Bench Press": "Incline Bench Press (Barbell)",
  "Dumbbell Incline Bench Press": "Incline Bench Press (Dumbbell)",
  "Smith Machine Incline Bench Press": "Incline Bench Press (Smith Machine)",
  "Smith Machine Bench Press": "Bench Press (Smith Machine)",
  "Smith Machine Bent Over Row": "Bent Over Row (Smith Machine)",
  "Dumbbell Bent Over Row": "Bent Over Row (Dumbbell)",
  "Dumbbell Bench Press": "Bench Press (Dumbbell)",
  "Barbell Bench Press": "Bench Press (Barbell)",
  "Machine Bench Press": "Chest Press (Machine)",
  "Dumbbell Pullover": "Pullover (Dumbbell)",
  "Dumbbell Decline Bench Press": "Decline Bench Press (Dumbbell)",
  "Barbell Decline Bench Press": "Decline Bench Press (Barbell)",
  "Standing Arnold Press": "Arnold Press (Dumbbell)",
  "Arnold Dumbbell Press": "Arnold Press (Dumbbell)",
  "Standing Dumbbell Shoulder Press": "Overhead Press (Dumbbell)",
  "Dumbbell Shoulder Press": "Overhead Press (Dumbbell)",
  "Dumbbell Shoulder Raise": "Lateral Raise (Dumbbell)",
  "Seated Barbell Shoulder Press": "Seated Overhead Press (Barbell)",
  "Machine Shoulder Press": "Seated Shoulder Press (Machine)",
  "Barbell Shoulder Press": "Overhead Press (Barbell)",
  "Smith Machine Overhead Shoulder Press": "Overhead Press (Smith Machine)",
  "Dumbbell Skullcrusher": "Skullcrusher (Dumbbell)",
  "EZ-Bar Skullcrusher": "Skullcrusher (Barbell)",
  Skullcrusher: "Skullcrusher (Dumbbell)",
  "Lat Pulldown": "Lat Pulldown (Cable)",
  "Machine Fly": "Chest Fly (Machine)",
  "Mid Cable Crossover Fly": "Cable Fly Crossovers",
  "Machine Rear Delt Fly": "Rear Delt Reverse Fly (Machine)",
  "Machine Leg Press": "Leg Press (Machine)",
  "Back Squat": "Squat (Barbell)",
  "Seated Back Extension": "Back Extension (Machine)",
  "Pause Back Squat": "Pause Squat (Barbell)",
  "Dumbbell Sumo Squat": "Sumo Squat (Dumbbell)",
  "Kettlebell Sumo Squat": "Sumo Squat (Kettlebell)",
  "Leg Extension": "Leg Extension (Machine)",
  "Seated Leg Curl": "Seated Leg Curl (Machine)",
  "Leg Curl": "Lying Leg Curl (Machine)",
  "Machine Hip Abductor": "Hip Abduction (Machine)",
  "Machine Tigh Abductor": "Hip Abduction (Machine)",
  "Machine Hip Adductor": "Hip Adduction (Machine)",
  "Calf Press": "Calf Press (Machine)",
  "Seated Machine Calf Press": "Calf Press (Machine)",
  "Standing Calf Press": "Calf Press (Machine)",
  "Dumbbell Lunge": "Lunge (Dumbbell)",
  "Barbell Lunge": "Lunge (Barbell)",
  "Side Lunge": "Lateral Lunge",
  "EZ-Bar Curl": "EZ Bar Biceps Curl",
  "Close-Grip EZ-Bar Curl": "EZ Bar Biceps Curl",
  "Cable Rope Tricep Extension": "Triceps Extension (Cable)",
  "Cable Tricep Extension": "Triceps Extension (Cable)",
  "Cable One Arm Tricep Side Extension": "Triceps Extension (Cable)",
  "Cable Rope Overhead Triceps Extension": "Triceps Extension (Cable)",
  "Cable Tricep Pushdown": "Triceps Rope Pushdown",
  "Triceps Pressdown": "Triceps Pushdown",
  "Seated Tricep Press": "Triceps Extension (Machine)",
  "Standing Dumbbell Tricep Extension": "Triceps Extension (Dumbbell)",
  "Single Arm Dumbbell Tricep Extension":
    "Single Arm Tricep Extension (Dumbbell)",
  "Bent Over Barbell Row": "Bent Over Row (Barbell)",
  "Cable Row": "Seated Cable Row - Bar Grip",
  "Cable Row with Squat": "Squat Row",
  "Cable Upright Row": "Upright Row (Cable)",
  "Upright Row": "Upright Row (Barbell)",
  "T-Bar Row": "T Bar Row",
  "Machine Row": "Seated Row (Machine)",
  "Straight-Arm Pulldown": "Rope Straight Arm Pulldown",
  "Hammerstrength High Row": "Iso-Lateral High Row (Machine)",
  "Hammerstrength Iso Row": "Iso-Lateral Row (Machine)",
  "Hammerstrength Chest Press": "Iso-Lateral Chest Press (Machine)",
  "Hammerstrength Incline Chest Press": "Incline Chest Press (Machine)",
  "Dumbbell Shrug": "Shrug (Dumbbell)",
  "Barbell Shrug": "Shrug (Barbell)",
  "Cable Shrug": "Shrug (Cable)",
  "Dumbbell Lateral Raise": "Lateral Raise (Dumbbell)",
  "Lateral Raise": "Lateral Raise (Dumbbell)",
  "Side Lateral Raise": "Lateral Raise (Dumbbell)",
  "Cable Lateral Raise": "Lateral Raise (Cable)",
  "Machine Lateral Raise": "Lateral Raise (Machine)",
  "Smith Machine Shrug": "Shrug (Smith Machine)",
  "Smith Machine Behind the Back Shrug Shrug": "Shrug (Smith Machine)",
  Deadlift: "Deadlift (Barbell)",
  "Romanian Deadlift": "Romanian Deadlift (Barbell)",
  "Dumbbell Romanian Deadlift": "Romanian Deadlift (Dumbbell)",
  "Low Cable Chest Fly": "Low Cable Fly Crossovers",
  "Cable Crossover Fly": "Cable Fly Crossovers",
  "Dumbbell Fly": "Chest Fly (Dumbbell)",
  "Incline Dumbbell Row": "Chest Supported Incline Row (Dumbbell)",
  "Dumbbell Incline Fly": "Incline Chest Fly (Dumbbell)",
  "Dumbbell Bicep Curl": "Bicep Curl (Dumbbell)",
  "Cable Bicep Curl": "Bicep Curl (Cable)",
  "Barbell Curl": "Bicep Curl (Barbell)",
  "Dumbbell Preacher Curl": "Preacher Curl (Dumbbell)",
  "Preacher Curl": "Preacher Curl (Barbell)",
  "Machine Preacher Curl": "Preacher Curl (Machine)",
  "Reverse Barbell Curl": "Reverse Curl (Barbell)",
  Crunches: "Crunch",
  "Incline Push Up": "Incline Push Ups",
  "Waiter Curls": "Bicep Curl (Dumbbell)",
  "Assisted Pull Up": "Pull Up (Assisted)",
  "Hammer Curls": "Hammer Curl (Dumbbell)",
  "Cobra Triceps Extension": "Kneeling Push Up",
  "Dumbbell Front Raise": "Front Raise (Dumbbell)",
  "Side Laterals to Front Raise": "Front Raise (Dumbbell)",
  "Knee Raise": "Hanging Knee Raise",
  "Palms-Up Dumbbell Wrist Curl": "Seated Palms Up Wrist Curl",
  "Palms-Down Dumbbell Wrist Curl": "Seated Palms Up Wrist Curl",
  "Palms-Down Barbell Wrist Curl": "Seated Wrist Extension (Barbell)",
  "Palms-Up Barbell Wrist Curl": "Seated Wrist Extension (Barbell)",
  "Incline Dumbbell Curl": "Seated Incline Curl (Dumbbell)",
  "Reverse Dumbbell Curl": "Reverse Curl (Dumbbell)",
  "Machine Tricep Dip": "Seated Dip Machine",
  "Close-Grip Bench Press": "Bench Press - Close Grip (Barbell)",
  "Dumbbell No Money Curls": "Bicep Curl (Dumbbell)",
  "Cable Rear Delt Fly": "Rear Delt Reverse Fly (Cable)",
  "V-Bar Pulldown": "Lat Pulldown - Close Grip (Cable)",
  "Hand Release Push Up": "Push Up",
  "Cross Body Hammer Curls": "Cross Body Hammer Curl",
  "Ab Crunch Machine": "Crunch (Machine)",
  "Reverse Grip Pull Down": "Reverse Grip Lat Pulldown (Cable)",
  "Seated Dumbbell Curl": "Bicep Curl (Dumbbell)",
  "Assisted Dip": "Triceps Dip (Assisted)",
  "Air Squats": "Squat (Bodyweight)",
  "Dumbbell Back Fly": "Chest Supported Reverse Fly (Dumbbell)",
  "Cycling - Stationary": "Spinning",
  "Walking - Treadmill": "Treadmill",
  "Push Up on Knees": "Kneeling Push Up",
} as const;
